package dmm.productfactory.applicationData;

public final class ThingsToDo {

    public static String[] getPlayForChildren(){
        return new String[] {
                "Zabawa w skojarzenia",
                "Poszukiwanie skarbów",
                "Gry planszowe",
                "Skoki przez płaską drabinkę (np. z gazety)",
                "Skoki przez linkę",
                "Kto wyżej podskoczy i narysuje linię",
                "Spacer na niby (wymyślamy co widzimy i co robimy)",
                "Przeciąganie liny",
                "Raz, dwa, trzy – baba jaga patrzy",
                "Ciuciubabka",
                "Baloniku mój malutki",
                "Gra w klasy",
                "Celowanie",
                "Rowerek bez pedałów",
                "Hulajnoga, rower, rolki",
                "Tor przeszkód",
                "Slalom",
                "Kalambury",
                "Tworzenie zwierzątek z rolek po papierze toaletowym",
                "Kto dalej popchnie mały przedmiot",
                "Kto dalej rzuci piłkę",
                "Origami",
                "Samoloty z papieru",
                "Pieczenie ciasteczek",
                "Podlewanie kwiatów",
                "Zabawa w ciepło – zimno",
                "Zabawa w zgaduj zgadula",
                "Zabawa w pomidora",
                "Figurki z masy solnej",
                "Piasek kinetyczny",
                "Klocki",
                "Ciastolina",
                "Odbijanie balonów",
                "Puszczanie baniek mydlanych",
                "Odrysowywanie cieni",
                "Okazjonalne ozdoby lub kartki",
                "Rysowanie po kartce pokrytej wzorem z białej świecy",
                "Rysowanie po kartce położonej na wypukłym motywie np. monecie",
                "Czytanie książki",
                "Wspólne wymyślanie historii",
                "Zabawa w chowanego",
                "Skakanie na piłce",
                "Wycinanie obrazków z gazet",
                "Malowanie farbami",
                "Pieczątki",
                "Budowanie wysokiej wieży (nie koniecznie z klocków",
                "Wyścigi małych samochodzików",
                "Puzzle",
                "Śpiewanie",
                "Tańczenie",
                "Turlanie",
                "Zawijanie w koc (naleśnik)",
                "Huśtanie",
                "Rysowanie stopami",
                "Rowerek",
                "Samolot",
                "Wymyślanie rymowanek",
                "Rozpoznawanie przedmiotów z worka po dotyku"

        };
    }


    public static String[] getThingsToDo(){
        return new String[] {
                "Rozmarz się o swoim nowym projekcie",
                "Zaplanuj ubranie na jakąś okazję",
                "Obejrzyj ubrania w swoim ulubionym sklepie",
                "Tańcz do spokojnej muzyki",
                "Tańcz do wesołej muzyki",
                "Przeczytaj fragment Biblii",
                "Pomaluj paznokcie",
                "Przeczytaj fragment książki, która jest aktualnie otwarta w Kindle",
                "Obejrzyj film",
                "Dodaj coś do kodu swojej aplikacji",
                "Zrób notatkę wizualną do aktualnie słuchanego podcastu",
                "Zrób lekcję języka obcego",
                "Przeczytaj fragment książki branżowej",
                "Wypij filiżankę słodkiej herbaty",
                "Wypij kubek mleka",
                "Wypij szklankę wody",
                "Wypij filiżankę ziołowej herbaty",
                "Zrób lekcję aktualnego kursu online",
                "Przygotuj koktajl owocowy",
                "Zaprojekuj przestrzeń w swoim mieszkaniu",
                "Sprawdź porządek w szafie",
                "Sprawdź porządek w aneksie",
                "Sprawdź porządek w salonie",
                "Sprawdź porządek w łazience",
                "Sprawdź porządek na korytarzu",
                "Przeczytaj zalegające maile",
                "Sprawdź stan butów",
                "Posłuchaj muzyki musicalowej",
                "Posłuchaj muzyki filmowej",
                "Posłuchaj poezji śpiewanej",
                "Posłuchaj muzyki tanecznej",
                "Przytul się",
                "Przeczytaj fragment beletrystyki",
                "Przejrzyj zabawki dzieci",
                "Pomyśl o nowych zabawkach dla dzieci",
                "Dodaj zdjęcie na Instagram",
                "Przeczytaj artykuł z zakładek",
                "Zrób kilka ćwiczeń rozciągających",
                "Zaśpiewaj bardzo głośno radosną piosenkę",
                "Zaśpiewaj wiersz",
                "Pomódl się",
                "Zrób listę filmów do obejrzenia",
                "Zrób listę książek do przeczytania",
                "Uporządkuj książki",
                "Pokoloruj kolorowankę",
                "Pomaluj kolorowankę",
                "Narysuj to, co widzisz",
                "Namaluj to, co widzisz",
                "Znajdź przyjemny zapach",
                "Napisz list",
                "Przygotuj kartkę okolicznościową",
                "Zapisz zdanie, które od dawna chodzi Ci po głowie",
                "Posłuchaj podcastu",
                "Przeczytaj artykół z bloga Domowe Zawirowania",
                "Zadbaj o swoje dłonie",
                "Zadbaj o swoje stopy",

        };
    }
}
