package dmm.productfactory.applicationData;

public final class ThingsToDo {

    public static String[] getThingsToDo(){
        return new String[] {
                "Rozmarz się o swoim nowym projekcie",
                "Zaplanuj ubranie na jakąś okazję",
                "Obejrzyj ubrania w swoim ulubionym sklepie",
                "Tańcz do spokojnej muzyki",
                "Tańcz do wesołej muzyki",
                "Przeczytaj fragment Biblii",
                "Pomaluj paznokcie",
                "Przeczytaj fragment książki, która jest aktualnie otwarta w Kindle",
                "Obejrzyj film",
                "Dodaj coś do kodu swojej aplikacji",
                "Zrób notatkę wizualną do aktualnie słuchanego podcastu",
                "Zrób lekcję języka obcego",
                "Przeczytaj fragment książki branżowej",
                "Wypij filiżankę słodkiej herbaty",
                "Wypij kubek mleka",
                "Wypij szklankę wody",
                "Wypij filiżankę ziołowej herbaty",
                "Zrób lekcję aktualnego kursu online",
                "Przygotuj koktajl owocowy",
                "Zaprojekuj przestrzeń w swoim mieszkaniu",
                "Sprawdź porządek w szafie",
                "Sprawdź porządek w aneksie",
                "Sprawdź porządek w salonie",
                "Sprawdź porządek w łazience",
                "Sprawdź porządek na korytarzu",
                "Przeczytaj zalegające maile",
                "Sprawdź stan butów",
                "Posłuchaj muzyki musicalowej",
                "Posłuchaj muzyki filmowej",
                "Posłuchaj poezji śpiewanej",
                "Posłuchaj muzyki tanecznej",
                "Przytul się",
                "Przeczytaj fragment beletrystyki",
                "Przejrzyj zabawki dzieci",
                "Pomyśl o nowych zabawkach dla dzieci",
                "Dodaj zdjęcie na Instagram",
                "Przeczytaj artykuł z zakładek",
                "Zrób kilka ćwiczeń rozciągających",
                "Zaśpiewaj bardzo głośno radosną piosenkę",
                "Zaśpiewaj wiersz",
                "Pomódl się",
                "Zrób listę filmów do obejrzenia",
                "Zrób listę książek do przeczytania",
                "Uporządkuj książki",
                "Pokoloruj kolorowankę",
                "Pomaluj kolorowankę",
                "Narysuj to, co widzisz",
                "Namaluj to, co widzisz",
                "Znajdź przyjemny zapach",
                "Napisz list",
                "Przygotuj kartkę okolicznościową",
                "Zapisz zdanie, które od dawna chodzi Ci po głowie",
                "Posłuchaj podcastu",
                "Przeczytaj artykół z bloga Domowe Zawirowania",
                "Zadbaj o swoje dłonie",
                "Zadbaj o swoje stopy",

        };
    }
}
